cd "d:/Projects/K210/K210_Maix_Bit/SDK/lvgl/lvgl8-projects/k210-kendryte_dvp2lcd-standalone1.14/build"
SET ALLUSERSPROFILE=C:\ProgramData
SET AMDRMPATH=C:\Program Files\AMD\RyzenMaster\
SET APPDATA=C:\Users\GEM\AppData\Roaming
SET asl.log=Destination=file
SET BT_PANEL=D:\BtSoft\panel
SET BT_PYTHON=C:\Program Files\python
SET BT_SETUP=D:\BtSoft
SET ChocolateyInstall=C:\ProgramData\chocolatey
SET ChocolateyLastPathUpdate=132490542323525246
SET CommonProgramFiles=C:\Program Files\Common Files
SET CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
SET CommonProgramW6432=C:\Program Files\Common Files
SET COMPUTERNAME=GEM
SET ComSpec=C:\WINDOWS\system32\cmd.exe
SET DriverData=C:\Windows\System32\Drivers\DriverData
SET FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
SET FPS_BROWSER_USER_PROFILE_STRING=Default
SET HOMEDRIVE=C:
SET HOMEPATH=\Users\GEM
SET LOCALAPPDATA=C:\Users\GEM\AppData\Local
SET LOGONSERVER=\\GEM
SET NUMBER_OF_PROCESSORS=12
SET OneDrive=D:\OneDrive
SET OneDriveConsumer=D:\OneDrive
SET OS=Windows_NT
SET Path=d:\Projects\K210\K210_Maix_Bit\IDE\KendryteIDE\bin;d:\Projects\K210\K210_Maix_Bit\IDE\KendryteIDE\LocalPackage\toolchain\bin;d:\Projects\K210\K210_Maix_Bit\IDE\KendryteIDE\LocalPackage\cmake\bin;d:\Projects\K210\K210_Maix_Bit\IDE\KendryteIDE\LocalPackage\jlink;d:\Projects\K210\K210_Maix_Bit\IDE\KendryteIDE\LocalPackage\clang-format\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH
SET PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
SET PROCESSOR_ARCHITECTURE=AMD64
SET PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
SET PROCESSOR_LEVEL=23
SET PROCESSOR_REVISION=7100
SET ProgramData=C:\ProgramData
SET ProgramFiles=C:\Program Files
SET ProgramFiles(x86)=C:\Program Files (x86)
SET ProgramW6432=C:\Program Files
SET PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
SET PUBLIC=C:\Users\Public
SET SESSIONNAME=Console
SET SystemDrive=C:
SET SystemRoot=C:\WINDOWS
SET TEMP=C:\Users\GEM\AppData\Local\Temp
SET TMP=C:\Users\GEM\AppData\Local\Temp
SET UNRAR_LIB_PATH=C:\Program Files\python\Lib\site-packages\unrar\UnRAR.dll
SET USERDOMAIN=GEM
SET USERDOMAIN_ROAMINGPROFILE=GEM
SET USERNAME=GEM
SET USERPROFILE=C:\Users\GEM
SET VS100COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools\
SET VSCODE_CWD=C:\WINDOWS\system32
SET VSCODE_IPC_HOOK=\\.\pipe\3b024cfa4c2f410a59d15e4cf49c28cd-1.34.1-beta-main-sock
SET VSCODE_LOGS=D:\Projects\K210\K210_Maix_Bit\IDE\KendryteIDE\UserData\latest\user-data\logs\20230226T001210
SET VSCODE_NLS_CONFIG={"locale":"zh-cn","availableLanguages":{"*":"zh-cn"},"_languagePackId":"2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_translationsConfigFile":"D:\\Projects\\K210\\K210_Maix_Bit\\IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\tcf.json","_cacheRoot":"D:\\Projects\\K210\\K210_Maix_Bit\\IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_resolvedLanguagePackCoreLocation":"D:\\Projects\\K210\\K210_Maix_Bit\\IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\e4de46724de34a5f46541818e9fee25971ac9969","_corruptedFile":"D:\\Projects\\K210\\K210_Maix_Bit\\IDE\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\corrupted.info","_languagePackSupport":true}
SET VSCODE_NODE_CACHED_DATA_DIR=D:\Projects\K210\K210_Maix_Bit\IDE\KendryteIDE\UserData\latest\user-data\CachedData\e4de46724de34a5f46541818e9fee25971ac9969
SET VSCODE_PID=18624
SET VSCODE_PORTABLE=D:\Projects\K210\K210_Maix_Bit\IDE\KendryteIDE\UserData\latest
SET windir=C:\WINDOWS
SET PYTHONHOME=d:/Projects/K210/K210_Maix_Bit/IDE/KendryteIDE/LocalPackage/python2library
SET PYTHONPATH=d:/Projects/K210/K210_Maix_Bit/IDE/KendryteIDE/LocalPackage/python2library;d:/Projects/K210/K210_Maix_Bit/IDE/KendryteIDE/LocalPackage/toolchain/share/gdb/python
SET PYTHONDONTWRITEBYTECODE=yes
SET CMAKE_MAKE_PROGRAM=make
SET KENDRYTE_IDE=yes
SET LANG=en_US.utf-8
"d:/Projects/K210/K210_Maix_Bit/IDE/KendryteIDE/LocalPackage/cmake/bin/cmake.exe" --build d:/Projects/K210/K210_Maix_Bit/SDK/lvgl/lvgl8-projects/k210-kendryte_dvp2lcd-standalone1.14/build -- -j 11